fix: Mobile screen rotation fix
st3v3nmw/obsidian-spaced-repetition pull request #1194
Opened 2024-12-28 14:34 UTC by KyleKlus

This pr fixes the current visual bug, when the plugin is used on a mobile device in landscape mode (See pictures).
Further more this pr also adds a "how to develop & test ui changes" to the contribution page, so that these issues wont arise again in a future ui change.

## PC design

<img src="https://github.com/user-attachments/assets/dd4f70dd-6e37-4715-a7ea-e2811a047cc3" width="400px"><img>
_For reference: Old design used on a pc_

<img src="https://github.com/user-attachments/assets/aaeb86b5-d397-4fe2-a2b3-0a23fc5fd4e6" width="400px"><img>
_New design used on a pc_

## Mobile design

<img src="https://github.com/user-attachments/assets/98e149f3-cbf4-464e-9bb2-4003eafbfede" width="600px"><img>
_For reference: Old design on a mobile device in landscape mode with the visual bug_

<img src="https://github.com/user-attachments/assets/b77a99b7-74cb-4e1d-ac2a-1c9bb2efab8c" width="600px"><img>
_New design on a mobile device in landscape mode_

<img src="https://github.com/user-attachments/assets/73e66bb1-da5c-4edd-b807-9790d6158ab4" width="600px"><img>
_Old design on a small mobile device in landscape mode with visual bug_

<img src="https://github.com/user-attachments/assets/d0161916-da41-4646-baca-230d1b097af4" width="600px"><img>
_New design on a small mobile device in landscape mode_

## New contributing text

<img src="https://github.com/user-attachments/assets/b56bb623-ca0b-4118-a1f4-0cff50b3e2e1" width="700px"><img>

2024-12-28 15:06 UTC, KyleKlus commented
## The thought process behind the end design

The whole thing broke because I didnt check the mobile landscape mode, when I developed the more detailed session progress title text and didnt assume that someone moved everything around so dramatically.
Someone wanted to make room in the mobile landscape mode and has thus moved all the buttons to the side, to open up some space in the middle (see #990 & #998).

To fix this, I moved the progress text to the card context area, shrunk down the response buttons for small screens and only moved the upper control buttons to the left side in the landscape mode, such that more space is opened up for viewing the cards. I did my best to respect the wish to have more viewing space and at the same time to have a good and consistant design

2025-01-14 12:15 UTC, KyleKlus commented
The last commit changes the looks of the deck progress info a tiny bit(see pictures below).

**Changes:**

- _Deck progress info now with bold font weight:_

<img src="https://github.com/user-attachments/assets/a9ee1e83-7058-47bf-8e64-2bb55f0194fc" width="400px"/>

<br/>
<br/>

- _Chosen deck progress info now without sub deck counter if there are no subdecks:_

<img src="https://github.com/user-attachments/assets/e8bbfe78-9790-4b18-b291-accf09ed9c29" width="400px"/>

2025-01-26 12:41 UTC, bentoner commented
@KyleKlus Thanks for fixing this. Works for me on iPad and Desktop.

2025-02-02 13:34 UTC, st3v3nmw requested changes
Hi @KyleKlus, thanks for the fix!

My only question is, can we make the _card context_ always appear on a separate line on its own? Something like this:

![image](https://github.com/user-attachments/assets/c9b5000e-3fca-46f8-b42a-bef92e162bb7)

Currently, it moves to the bottom when the _card context_ is too long which is a bit distracting if it keeps switching places:

![image](https://github.com/user-attachments/assets/4d7a9427-bb4c-424e-89fd-b5871cfed0d1)

2025-02-02 15:09 UTC, KyleKlus commented
Sure, let's do that 😊.

I'll work on it either this evening or tomorrow, so it should be ready until Tuesday.

2025-02-04 03:41 UTC, st3v3nmw approved these changes
LGTM, thank you for the UI fixes!

2025-02-04 03:42 UTC, merged