chore(git hook): add precommit-hook to handle validation checks
st3v3nmw/obsidian-spaced-repetition pull request #903
Opened 2024-03-17 16:10 UTC by EspiraMarvin

- This change adds validation check for linting, formatting & test concurrently on commit

Fixes #880

2024-03-17 22:38 UTC, ronzulu commented
Hi @EspiraMarvin does this mean that the lint/test operations will occur whenever a developer pushes local commits to GitHub. I.e. these operations will occur regardless of whether or not there is an associated PR?

Thanks
Ronny

2024-03-19 05:17 UTC, st3v3nmw requested changes

2024-03-19 05:17 UTC, st3v3nmw commented on package-lock.json
Looks like you used `npm` instead of `pnpm`

2024-03-19 15:26 UTC, EspiraMarvin commented on package-lock.json
@st3v3nmw I'll change it to use pnpm

2024-03-19 21:28 UTC, ronzulu commented
> @ronzulu Yes, according to the PR, the operations will run regardless of whether or not there is an associated PR.

Thanks. I think this is really helpful.

2024-09-22 17:13 UTC, st3v3nmw commented
@EspiraMarvin 👀 ...

2024-10-19 18:37 UTC, EspiraMarvin commented
> @EspiraMarvin 👀 ...

@st3v3nmw  this is ready

2024-10-20 06:11 UTC, st3v3nmw approved these changes
LGTM, thanks!

2024-10-20 06:12 UTC, merged